### ISSUE TITLE
Which genbank database is needed?

### ISSUE THREAD

**Issue by rvosa** [o-william-white/skim2phylo#8]
We have a genbank nr release that we timestamped 2022-03-16 and that we use as a blast database. Will that do? Or should we have a reference data set, maybe on Zenodo?

**Comment by o-william-white** [comment]
That will be fine in the meantime, it's just to get a rough idea of taxonomy of the sequence to identifiy obvious contaminants. Ultimately yes a reference database would be a good idea. The NCBI nt database is large and not all users will have access to it.

**Comment by o-william-white** [comment]
>  nr release

As it stands the script requires a nt database. I think nr is protein. Do you have a nt database available? 

If not we could edit your Snakefile to run a blastx search instead?

**Comment by rvosa** [comment]
nr here refers to non-redundant, sorry. It's nucleotide so we can run blastn on it like in the Snakefile.

**Comment by o-william-white** [comment]
Hi @rvosa, I updated the pipeline so it now downloads smaller blast databases specific to mitochondrial and ribosomal sequences https://zenodo.org/records/8424777. Hopefully this helps if users do not have access to nt or nr databses already. Hope you are well
